// <auto-generated />
using System;
using AspnetCoreMvcStarter.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspnetCoreMvcStarter.Migrations
{
    [DbContext(typeof(AspnetCoreMvcStarterContext))]
    [Migration("20250116071153_under")]
    partial class under
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.CrowdFunding.DashboardData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("ApprovedByBroker")
                        .HasColumnType("REAL");

                    b.Property<double>("FundingApprovedByFarabourse")
                        .HasColumnType("REAL");

                    b.Property<double>("FundingFinished")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherApprovedByBroker")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherFundingApprovedByFarabourse")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherFundingFinished")
                        .HasColumnType("REAL");

                    b.Property<double>("OtherStarted")
                        .HasColumnType("REAL");

                    b.Property<double>("Started")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("DashboardData");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.CrowdFunding.ProjectInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionAgent")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionIfb")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyNationalID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompanyUnitCounts")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CrowdFundingType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EconomicID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GuaranteeType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IndustryGroupDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LegalPersonMaximumAvailablePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LegalPersonMinimumAvailablePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinimumRequiredPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PersianApprovedSymbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersianName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersianSubject")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProjectEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProjectStartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealPersonMaximumAvailablePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RealPersonMinimumAvailablePrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubIndustryGroupDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnderwritingApprovedStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnderwritingDuration")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UnderwritingEndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UnderwritingStartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("ProjectInfos");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.CrowdFunding.ProjectView", b =>
                {
                    b.Property<int>("شناسه_طرح")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("تاریخ_اتمام_پروژه")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("تاریخ_تایید_شده_شروع_جمع_آوری_وجوه")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("تاریخ_ثبت_شرکت")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("تاریخ_شروع_پروژه")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("تاریخ_پیشنهادی_شروع_جمع_آوری_وجوه")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("تاریخ_پیشنهادی_پایان_جمع_آوری_وجوه")
                        .HasColumnType("TEXT");

                    b.Property<int>("تعداد_گواهی_شراکت_متقاضی")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("حداقل_مبلغ_سرمایه_گذاری_برای_تامین_کننده_حقوقی")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("حداقل_مبلغ_سرمایه_گذاری_برای_تامین_کننده_حقیقی")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("حداقل_مبلغ_مورد_نیاز_جهت_موفقیت_تامین_مالی")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("حداکثر_مبلغ_سرمایه_گذاری_برای_تامین_کننده_حقوقی")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("حداکثر_مبلغ_سرمایه_گذاری_برای_تامین_کننده_حقیقی")
                        .HasColumnType("TEXT");

                    b.Property<int>("دوره_جمع_آوری_وجوه")
                        .HasColumnType("INTEGER");

                    b.Property<string>("زیرگروه_صنعت")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("شماره_ثبت_شرکت")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("شناسه_ملی")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("لینک_عامل")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("مبلغ_مورد_نیاز")
                        .HasColumnType("TEXT");

                    b.Property<string>("موضوع_طرح")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نام_سکو")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نام_شرکت")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نام_طرح_یا_پروژه")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نام_عامل")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نماد_طرح")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نوع_تامین_مالی_جمعی")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نوع_شخصیت_حقوقی_شرکت")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("نوع_وثیقه")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("وضعیت_طرح")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("کارمزد_عامل")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("کارمزد_فرابورس")
                        .HasColumnType("TEXT");

                    b.Property<string>("کد_اقتصادی_شرکت")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("کد_پستی_شرکت")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("گروه_صنعت")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("شناسه_طرح");

                    b.ToTable("ProjectViews");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.CrowdFunding.UnderwritingByYear", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalPrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("UnderwritingByYears");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Benefit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ActualRaisedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Applicant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApprovalDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CollateralType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinancialInstitutionID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FinancialInstitutionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FundCollectionDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("IndividualContributorsCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("TEXT");

                    b.Property<int>("LegalContributorsCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LegalRaisedAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectEndDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectStartDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalFundingRequired")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalRaisedAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.QuestionHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isDelete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("response")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("selectedOption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("QuestionHistories");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.TextSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TextSegments");
                });

            modelBuilder.Entity("AspnetCoreMvcStarter.Models.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Total")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
